spring.datasource.url=jdbc:mysql://localhost:3306/mpa_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=mpa_app_user
spring.datasource.password=3Fv!9xP@2Lm#Q7zT8kW

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

server.port=8080